### ISSUE TITLE
Coordinate dimensions other than XY fails

### ISSUE THREAD

**Issue by rotsee** [gagan-bansal/geojson2svg#20]
It seems like the only coordinate dimensions that work are XY (not e.g. XYZ, XYM). Not sure this that is a bug or a feature not yet implemented. For XYZ- coordinates the script fails with the error `TypeError: coordinates.map is not a function` at `/reproject/index.js:13:22`

**Comment by gagan-bansal** [comment]
I have not checked for coordinates with  Z/M, though it should work. 

Your issue seems with reproject lib. If you are checking my example, there I had used [perliedman/reproject](https://github.com/perliedman/reproject) and that doesn't seem support XYZ/XYM.
 
Please try another reproject lib like [@turf/projection](https://www.npmjs.com/package/@turf/projection) and check if your issue is resolved.

I would like to fix the issue if its with geojson2svg.

**Comment by rotsee** [comment]
Oh, my bad; I was reporting this in the wrong place. Closing and moving!

**Comment by gagan-bansal** [comment]
No prob, any time you like to discuss regarding this, feel free. Important thing is your issue should be resolved with geojson2svg or associated module too.
